version: '3.8'

services:
  # Core Service - Base models and utilities
  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    container_name: trading-core-service
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=demo
      - DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Market Data Service - Price data provider
  market-service:
    build:
      context: ./market-service
      dockerfile: Dockerfile
    container_name: trading-market-service
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=demo
      - DEBUG=true
      - CORE_SERVICE_URL=http://core-service:8001
    depends_on:
      - core-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Redis for caching and pub/sub
  redis:
    image: redis:7-alpine
    container_name: trading-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
